// threshold-tracker/apps/web/src/app/features/register/register.component.ts
import { Component, inject, signal } from '@angular/core';
import { Router, RouterLink } from '@angular/router';
import { AuthService } from '../../services/auth.service';

@Component({
  selector: 'app-register',
  standalone: true,
  imports: [RouterLink],
  templateUrl: './register.component.html',
})
export class RegisterComponent {
  private authService = inject(AuthService);
  private router = inject(Router);

  displayName = signal('');
  email = signal('');
  password = signal('');
  error = signal('');
  loading = signal(false);

  onSubmit() {
    if (!this.displayName() || !this.email() || !this.password()) return;
    this.loading.set(true);
    this.error.set('');

    this.authService.register(this.displayName(), this.email(), this.password()).subscribe({
      next: () => this.router.navigate(['/dashboard']),
      error: (err) => {
        this.error.set(err.error?.detail ?? 'Registration failed. Please try again.');
        this.loading.set(false);
      }
    });
  }
}

<div class="min-h-screen bg-[#08080d] flex items-center justify-center px-4">
  <div class="w-full max-w-md">
    <div class="text-center mb-8">
      <div class="w-12 h-12 rounded-xl bg-gradient-to-br from-violet-500 to-cyan-500 flex items-center justify-center mx-auto mb-4">
        <svg xmlns="http://www.w3.org/2000/svg" class="w-6 h-6 text-white" viewBox="0 0 24 24"
          fill="none" stroke="currentColor" stroke-width="2">
          <circle cx="12" cy="12" r="10"/><line x1="22" y1="12" x2="18" y2="12"/>
          <line x1="6" y1="12" x2="2" y2="12"/><line x1="12" y1="6" x2="12" y2="2"/>
          <line x1="12" y1="22" x2="12" y2="18"/>
        </svg>
      </div>
      <h1 class="text-2xl font-bold text-white">Create account</h1>
      <p class="text-white/40 text-sm mt-1">Start tracking your aim performance</p>
    </div>

    <div class="bg-white/[0.03] border border-white/10 rounded-2xl p-6">
      @if (error()) {
        <div class="bg-red-500/10 border border-red-500/20 text-red-400 text-sm rounded-lg px-4 py-3 mb-4">
          {{ error() }}
        </div>
      }

      <div class="space-y-4">
        <div>
          <label class="text-white/60 text-xs uppercase tracking-wider block mb-2">Display Name</label>
          <input [value]="displayName()" (input)="displayName.set($any($event.target).value)"
            placeholder="Your name"
            class="w-full px-3 py-2 bg-white/5 border border-white/10 rounded-lg text-white placeholder-white/20 outline-none focus:border-white/20" />
        </div>
        <div>
          <label class="text-white/60 text-xs uppercase tracking-wider block mb-2">Email</label>
          <input type="email" [value]="email()" (input)="email.set($any($event.target).value)"
            placeholder="you@example.com"
            class="w-full px-3 py-2 bg-white/5 border border-white/10 rounded-lg text-white placeholder-white/20 outline-none focus:border-white/20" />
        </div>
        <div>
          <label class="text-white/60 text-xs uppercase tracking-wider block mb-2">Password</label>
          <input type="password" [value]="password()" (input)="password.set($any($event.target).value)"
            placeholder="Min. 8 characters"
            class="w-full px-3 py-2 bg-white/5 border border-white/10 rounded-lg text-white placeholder-white/20 outline-none focus:border-white/20" />
        </div>
        <button (click)="onSubmit()" [disabled]="loading()"
          class="w-full py-2.5 bg-violet-600 hover:bg-violet-500 disabled:opacity-50 text-white rounded-lg font-medium transition-colors">
          @if (loading()) { Creating account... } @else { Create Account }
        </button>
      </div>

      <p class="text-center text-white/30 text-sm mt-4">
        Already have an account?
        <a routerLink="/login" class="text-violet-400 hover:text-violet-300">Sign in</a>
      </p>
    </div>
  </div>
</div>

// threshold-tracker/apps/web-react/src/features/register/Register.tsx
import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { useAuth } from '../../context/AuthContext';

export function Register() {
  const { register } = useAuth();
  const navigate = useNavigate();
  const [displayName, setDisplayName] = useState('');
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);

  async function onSubmit() {
    if (!displayName || !email || !password) return;
    setLoading(true);
    setError('');
    try {
      await register(displayName, email, password);
      navigate('/dashboard', { replace: true });
    } catch (err: unknown) {
      const e = err as { data?: { detail?: string } };
      setError(e?.data?.detail ?? 'Registration failed. Please try again.');
      setLoading(false);
    }
  }

  return (
    <div className="min-h-screen bg-[#08080d] flex items-center justify-center px-4">
      <div className="w-full max-w-md">
        <div className="text-center mb-8">
          <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-violet-500 to-cyan-500 flex items-center justify-center mx-auto mb-4">
            <svg xmlns="http://www.w3.org/2000/svg" className="w-6 h-6 text-white" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <circle cx="12" cy="12" r="10"/><line x1="22" y1="12" x2="18" y2="12"/>
              <line x1="6" y1="12" x2="2" y2="12"/><line x1="12" y1="6" x2="12" y2="2"/>
              <line x1="12" y1="22" x2="12" y2="18"/>
            </svg>
          </div>
          <h1 className="text-2xl font-bold text-white">Create account</h1>
          <p className="text-white/40 text-sm mt-1">Start tracking your aim performance</p>
        </div>

        <div className="bg-white/[0.03] border border-white/10 rounded-2xl p-6">
          {error && (
            <div className="bg-red-500/10 border border-red-500/20 text-red-400 text-sm rounded-lg px-4 py-3 mb-4">
              {error}
            </div>
          )}
          <div className="space-y-4">
            <div>
              <label className="text-white/60 text-xs uppercase tracking-wider block mb-2">Display Name</label>
              <input value={displayName} onChange={e => setDisplayName(e.target.value)}
                placeholder="Your name"
                className="w-full px-3 py-2 bg-white/5 border border-white/10 rounded-lg text-white placeholder-white/20 outline-none focus:border-white/20" />
            </div>
            <div>
              <label className="text-white/60 text-xs uppercase tracking-wider block mb-2">Email</label>
              <input type="email" value={email} onChange={e => setEmail(e.target.value)}
                placeholder="you@example.com"
                className="w-full px-3 py-2 bg-white/5 border border-white/10 rounded-lg text-white placeholder-white/20 outline-none focus:border-white/20" />
            </div>
            <div>
              <label className="text-white/60 text-xs uppercase tracking-wider block mb-2">Password</label>
              <input type="password" value={password} onChange={e => setPassword(e.target.value)}
                onKeyDown={e => e.key === 'Enter' && onSubmit()}
                placeholder="Min. 8 characters"
                className="w-full px-3 py-2 bg-white/5 border border-white/10 rounded-lg text-white placeholder-white/20 outline-none focus:border-white/20" />
            </div>
            <button onClick={onSubmit} disabled={loading}
              className="w-full py-2.5 bg-violet-600 hover:bg-violet-500 disabled:opacity-50 text-white rounded-lg font-medium transition-colors">
              {loading ? 'Creating account...' : 'Create Account'}
            </button>
          </div>
          <p className="text-center text-white/30 text-sm mt-4">
            Already have an account?{' '}
            <Link to="/login" className="text-violet-400 hover:text-violet-300">Sign in</Link>
          </p>
        </div>
      </div>
    </div>
  );
}
