// threshold-tracker/apps/web-react/src/components/Layout.tsx
import { useState } from 'react';
import { Link, NavLink, Outlet, useNavigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';

export function Layout() {
  const { isLoggedIn, user, logout, aimlabsUsername } = useAuth();
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
  const [showUserMenu, setShowUserMenu] = useState(false);
  const navigate = useNavigate();

  function handleLogout() {
    logout();
    navigate('/login');
  }

  return (
    <div className="min-h-screen bg-[#08080d] text-white">
      <header className="fixed top-0 left-0 right-0 z-50 bg-[#08080d]/80 backdrop-blur-xl border-b border-white/5">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 h-16 flex items-center justify-between">

          {/* Logo */}
          <Link to="/dashboard" className="flex items-center gap-2.5">
            <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-violet-500 to-cyan-500 flex items-center justify-center">
              <svg xmlns="http://www.w3.org/2000/svg" className="w-4 h-4 text-white" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <circle cx="12" cy="12" r="10"/><line x1="22" y1="12" x2="18" y2="12"/>
                <line x1="6" y1="12" x2="2" y2="12"/><line x1="12" y1="6" x2="12" y2="2"/>
                <line x1="12" y1="22" x2="12" y2="18"/>
              </svg>
            </div>
            <span className="font-bold text-lg tracking-tight hidden sm:block">ThresholdTracker</span>
          </Link>

          {/* Desktop Nav */}
          <nav className="hidden md:flex items-center gap-1">
            <NavLink to="/dashboard" className={({ isActive }) =>
              `flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium transition-colors ${isActive ? 'bg-white/10 text-white' : 'text-white/50 hover:text-white hover:bg-white/5'}`
            }>
              Dashboard
            </NavLink>
          </nav>

          {/* Right side */}
          <div className="flex items-center gap-3">
            {isLoggedIn ? (
              <div className="relative hidden md:block">
                <button
                  onClick={() => setShowUserMenu(v => !v)}
                  className="flex items-center gap-2 px-3 py-1.5 bg-white/5 hover:bg-white/10 border border-white/10 rounded-lg text-sm text-white transition-colors"
                >
                  <div className="w-6 h-6 rounded-full bg-gradient-to-br from-violet-500 to-cyan-500 flex items-center justify-center text-xs font-bold">
                    {(user?.displayName ?? '?').charAt(0).toUpperCase()}
                  </div>
                  <div className="flex items-center gap-2 text-sm">
                    <span className="text-white">{user?.displayName}</span>
                    {aimlabsUsername && (
                      <>
                        <span className="text-white/15">|</span>
                        <span className="flex items-center gap-1 text-white/40">
                          <img src="/aimlabs-icon.svg" alt="Aimlabs" className="w-3.5 h-3.5 opacity-60" />
                          {aimlabsUsername}
                        </span>
                      </>
                    )}
                  </div>
                </button>
                {showUserMenu && (
                  <div className="absolute right-0 top-full mt-2 w-48 bg-[#0f0f17] border border-white/10 rounded-xl shadow-xl overflow-hidden">
                    <Link to="/profile" onClick={() => setShowUserMenu(false)}
                      className="flex items-center gap-2 px-4 py-3 text-sm text-white/70 hover:text-white hover:bg-white/5 transition-colors">
                      Profile Settings
                    </Link>
                    <button onClick={handleLogout}
                      className="w-full flex items-center gap-2 px-4 py-3 text-sm text-red-400 hover:bg-red-400/10 transition-colors">
                      Sign Out
                    </button>
                  </div>
                )}
              </div>
            ) : (
              <div className="hidden md:flex items-center gap-2">
                <Link to="/login" className="px-3 py-1.5 text-sm text-white/60 hover:text-white transition-colors">Sign In</Link>
                <Link to="/register" className="px-3 py-1.5 bg-violet-600 hover:bg-violet-500 text-white text-sm rounded-lg font-medium transition-colors">Register</Link>
              </div>
            )}

            <button className="md:hidden p-2 text-white/40" onClick={() => setMobileMenuOpen(v => !v)}>
              {mobileMenuOpen ? (
                <svg xmlns="http://www.w3.org/2000/svg" className="w-5 h-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/>
                </svg>
              ) : (
                <svg xmlns="http://www.w3.org/2000/svg" className="w-5 h-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <line x1="3" y1="6" x2="21" y2="6"/><line x1="3" y1="12" x2="21" y2="12"/><line x1="3" y1="18" x2="21" y2="18"/>
                </svg>
              )}
            </button>
          </div>
        </div>

        {/* Mobile menu */}
        {mobileMenuOpen && (
          <div className="md:hidden border-t border-white/5 bg-[#08080d]/95 p-4 space-y-1">
            <Link to="/dashboard" onClick={() => setMobileMenuOpen(false)}
              className="flex items-center gap-3 px-4 py-3 rounded-lg text-sm font-medium text-white/50">Dashboard</Link>
            {isLoggedIn ? (
              <>
                <Link to="/profile" onClick={() => setMobileMenuOpen(false)}
                  className="flex items-center gap-3 px-4 py-3 rounded-lg text-sm font-medium text-white/50">Profile Settings</Link>
                <button onClick={handleLogout}
                  className="w-full flex items-center gap-3 px-4 py-3 rounded-lg text-sm font-medium text-red-400">Sign Out</button>
              </>
            ) : (
              <>
                <Link to="/login" onClick={() => setMobileMenuOpen(false)}
                  className="flex items-center gap-3 px-4 py-3 rounded-lg text-sm font-medium text-white/50">Sign In</Link>
                <Link to="/register" onClick={() => setMobileMenuOpen(false)}
                  className="flex items-center gap-3 px-4 py-3 rounded-lg text-sm font-medium text-violet-400">Register</Link>
              </>
            )}
          </div>
        )}
      </header>

      <main className="pt-16 min-h-screen">
        <Outlet />
      </main>
    </div>
  );
}

// threshold-tracker/apps/web/src/app/layout/layout.component.ts
import { Component, OnInit, signal, inject } from '@angular/core';
import { Router, NavigationEnd, RouterLink, RouterOutlet } from '@angular/router';
import { NgClass } from '@angular/common';
import { filter } from 'rxjs/operators';
import { AuthService } from '../services/auth.service';

@Component({
  selector: 'app-layout',
  standalone: true,
  imports: [RouterLink, RouterOutlet, NgClass],
  templateUrl: './layout.component.html',
})
export class LayoutComponent implements OnInit {
  private router = inject(Router);
  authService = inject(AuthService);

  mobileMenuOpen = signal(false);
  currentRoute = signal('');
  showUserMenu = signal(false);

  ngOnInit() {
    this.currentRoute.set(this.router.url);
    this.router.events.pipe(
      filter(e => e instanceof NavigationEnd)
    ).subscribe((e: any) => {
      this.currentRoute.set(e.url);
      this.showUserMenu.set(false);
    });
  }

  logout() {
    this.authService.logout();
    this.router.navigate(['/login']);
  }
}

<div class="min-h-screen bg-[#08080d] text-white">

  <!-- Header -->
  <header class="fixed top-0 left-0 right-0 z-50 bg-[#08080d]/80 backdrop-blur-xl border-b border-white/5">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 h-16 flex items-center justify-between">

      <!-- Logo -->
      <a routerLink="/dashboard" class="flex items-center gap-2.5">
        <div class="w-8 h-8 rounded-lg bg-gradient-to-br from-violet-500 to-cyan-500 flex items-center justify-center">
          <svg xmlns="http://www.w3.org/2000/svg" class="w-4 h-4 text-white" viewBox="0 0 24 24"
            fill="none" stroke="currentColor" stroke-width="2">
            <circle cx="12" cy="12" r="10"/><line x1="22" y1="12" x2="18" y2="12"/>
            <line x1="6" y1="12" x2="2" y2="12"/><line x1="12" y1="6" x2="12" y2="2"/>
            <line x1="12" y1="22" x2="12" y2="18"/>
          </svg>
        </div>
        <span class="font-bold text-lg tracking-tight hidden sm:block">ThresholdTracker</span>
      </a>

      <!-- Desktop Nav -->
      <nav class="hidden md:flex items-center gap-1">
        <a routerLink="/dashboard"
          class="flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium transition-colors"
          [ngClass]="currentRoute().includes('dashboard') ? 'bg-white/10 text-white' : 'text-white/50 hover:text-white hover:bg-white/5'">
          Dashboard
        </a>
      </nav>

      <!-- Right side -->
      <div class="flex items-center gap-3">
        <!-- Auth controls -->
        @if (authService.isLoggedIn()) {
          <div class="relative hidden md:block">
            <button (click)="showUserMenu.set(!showUserMenu())"
              class="flex items-center gap-2 px-3 py-1.5 bg-white/5 hover:bg-white/10 border border-white/10 rounded-lg text-sm text-white transition-colors">
              <div class="w-6 h-6 rounded-full bg-gradient-to-br from-violet-500 to-cyan-500 flex items-center justify-center text-xs font-bold">
                {{ (authService.currentUser()?.displayName ?? '?').charAt(0).toUpperCase() }}
              </div>
              {{ authService.currentUser()?.displayName }}
            </button>
            @if (showUserMenu()) {
              <div class="absolute right-0 top-full mt-2 w-48 bg-[#0f0f17] border border-white/10 rounded-xl shadow-xl overflow-hidden">
                <a routerLink="/profile"
                  class="flex items-center gap-2 px-4 py-3 text-sm text-white/70 hover:text-white hover:bg-white/5 transition-colors">
                  Profile Settings
                </a>
                <button (click)="logout()"
                  class="w-full flex items-center gap-2 px-4 py-3 text-sm text-red-400 hover:bg-red-400/10 transition-colors">
                  Sign Out
                </button>
              </div>
            }
          </div>
        } @else {
          <div class="hidden md:flex items-center gap-2">
            <a routerLink="/login"
              class="px-3 py-1.5 text-sm text-white/60 hover:text-white transition-colors">
              Sign In
            </a>
            <a routerLink="/register"
              class="px-3 py-1.5 bg-violet-600 hover:bg-violet-500 text-white text-sm rounded-lg font-medium transition-colors">
              Register
            </a>
          </div>
        }

        <button class="md:hidden p-2 text-white/40" (click)="mobileMenuOpen.set(!mobileMenuOpen())">
          @if (!mobileMenuOpen()) {
            <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5" viewBox="0 0 24 24"
              fill="none" stroke="currentColor" stroke-width="2">
              <line x1="3" y1="6" x2="21" y2="6"/><line x1="3" y1="12" x2="21" y2="12"/>
              <line x1="3" y1="18" x2="21" y2="18"/>
            </svg>
          } @else {
            <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5" viewBox="0 0 24 24"
              fill="none" stroke="currentColor" stroke-width="2">
              <line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/>
            </svg>
          }
        </button>
      </div>
    </div>

    <!-- Mobile Nav -->
    @if (mobileMenuOpen()) {
      <div class="md:hidden border-t border-white/5 bg-[#08080d]/95 p-4 space-y-1">
        <a routerLink="/dashboard" (click)="mobileMenuOpen.set(false)"
          class="flex items-center gap-3 px-4 py-3 rounded-lg text-sm font-medium text-white/50">
          Dashboard
        </a>
        @if (authService.isLoggedIn()) {
          <a routerLink="/profile" (click)="mobileMenuOpen.set(false)"
            class="flex items-center gap-3 px-4 py-3 rounded-lg text-sm font-medium text-white/50">
            Profile Settings
          </a>
          <button (click)="logout()"
            class="w-full flex items-center gap-3 px-4 py-3 rounded-lg text-sm font-medium text-red-400">
            Sign Out
          </button>
        } @else {
          <a routerLink="/login" (click)="mobileMenuOpen.set(false)"
            class="flex items-center gap-3 px-4 py-3 rounded-lg text-sm font-medium text-white/50">
            Sign In
          </a>
          <a routerLink="/register" (click)="mobileMenuOpen.set(false)"
            class="flex items-center gap-3 px-4 py-3 rounded-lg text-sm font-medium text-violet-400">
            Register
          </a>
        }
      </div>
    }
  </header>

  <!-- Page Content -->
  <main class="pt-16 min-h-screen">
    <router-outlet></router-outlet>
  </main>
</div>
