// threshold-tracker/apps/web/src/app/components/score-history-table/score-history-table.component.ts
import { Component, Input, signal, computed } from '@angular/core';
import { PlayAttempt } from '../../models/score.model';
import { format } from 'date-fns';

@Component({
  selector: 'app-score-history-table',
  standalone: true,
  imports: [],
  templateUrl: './score-history-table.component.html',
})
export class ScoreHistoryTableComponent {
  @Input() set scores(value: PlayAttempt[]) { this._scores.set(value); this.page.set(1); }
  @Input() threshold = 0;

  private _scores = signal<PlayAttempt[]>([]);

  readonly pageSize = 25;
  page = signal(1);

  totalCount = computed(() => this._scores().length);
  totalPages = computed(() => Math.max(1, Math.ceil(this.totalCount() / this.pageSize)));
  firstItem = computed(() => (this.page() - 1) * this.pageSize + 1);
  lastItem = computed(() => Math.min(this.page() * this.pageSize, this.totalCount()));

  // Scores are sorted oldest→newest; table shows newest first
  pagedScores = computed(() => {
    const all = [...this._scores()].reverse();
    const start = (this.page() - 1) * this.pageSize;
    return all.slice(start, start + this.pageSize);
  });

  loadPage(p: number) {
    this.page.set(Math.max(1, Math.min(p, this.totalPages())));
  }

  formatDate(d: string) { return format(new Date(d), 'dd/MM/yyyy HH:mm'); }
}

@if (totalCount() === 0) {
  <div class="text-center py-12 text-white/20 text-sm">
    No scores recorded yet
  </div>
}

@if (totalCount() > 0) {
  <div class="overflow-x-auto">
    <table class="w-full text-sm">
      <thead>
        <tr class="text-white/30 text-xs uppercase tracking-wider border-b border-white/5">
          <th class="text-left py-3 px-4 font-medium">#</th>
          <th class="text-left py-3 px-4 font-medium">Score</th>
          @if (threshold > 0) {
            <th class="text-center py-3 px-2 font-medium">THR</th>
          }
          <th class="text-left py-3 px-4 font-medium">Date</th>
        </tr>
      </thead>
      <tbody>
        @for (s of pagedScores(); track s.played_at; let i = $index) {
          <tr class="border-b border-white/5 hover:bg-white/[0.02] transition-colors"
            [class.text-violet-400]="threshold > 0 && s.score >= threshold">
            <td class="py-3 px-4 text-white/30">{{ totalCount() - firstItem() - i + 1 }}</td>
            <td class="py-3 px-4">
              <span class="font-medium">{{ s.score.toLocaleString() }}</span>
            </td>
            @if (threshold > 0) {
              <td class="py-3 px-2 text-center text-base leading-none">
                @if (s.score >= threshold) {
                  <span class="text-emerald-400">✓</span>
                } @else {
                  <span class="text-white/20">✗</span>
                }
              </td>
            }
            <td class="py-3 px-4 text-white/40">{{ formatDate(s.played_at) }}</td>
          </tr>
        }
      </tbody>
    </table>
  </div>

  @if (totalPages() > 1) {
    <div class="flex items-center justify-between px-4 py-3 border-t border-white/5">
      <span class="text-white/30 text-xs">
        {{ firstItem() }}–{{ lastItem() }} of {{ totalCount() }}
      </span>
      <div class="flex items-center gap-2">
        <button (click)="loadPage(page() - 1)" [disabled]="page() === 1"
          class="px-3 py-1 text-xs text-white/40 hover:text-white disabled:opacity-30 disabled:cursor-not-allowed bg-white/5 hover:bg-white/10 rounded-lg transition-colors">
          Prev
        </button>
        <span class="text-white/30 text-xs px-1">{{ page() }} / {{ totalPages() }}</span>
        <button (click)="loadPage(page() + 1)" [disabled]="page() === totalPages()"
          class="px-3 py-1 text-xs text-white/40 hover:text-white disabled:opacity-30 disabled:cursor-not-allowed bg-white/5 hover:bg-white/10 rounded-lg transition-colors">
          Next
        </button>
      </div>
    </div>
  }
}

// threshold-tracker/apps/web-react/src/components/ScoreHistoryTable.tsx
import { useState, useMemo, useEffect } from 'react';
import { format } from 'date-fns';
import { PlayAttempt } from '../models/score';

interface Props {
  scores: PlayAttempt[];
  threshold: number;
}

const PAGE_SIZE = 25;

export function ScoreHistoryTable({ scores, threshold }: Props) {
  const [page, setPage] = useState(1);

  // Reset page when scores change
  useEffect(() => { setPage(1); }, [scores]);

  const totalCount = scores.length;
  const totalPages = Math.max(1, Math.ceil(totalCount / PAGE_SIZE));
  const firstItem = (page - 1) * PAGE_SIZE + 1;
  const lastItem = Math.min(page * PAGE_SIZE, totalCount);

  const pagedScores = useMemo(() => {
    const all = [...scores].reverse();
    const start = (page - 1) * PAGE_SIZE;
    return all.slice(start, start + PAGE_SIZE);
  }, [scores, page]);

  function loadPage(p: number) {
    setPage(Math.max(1, Math.min(p, totalPages)));
  }

  if (totalCount === 0) {
    return <div className="text-center py-12 text-white/20 text-sm">No scores recorded yet</div>;
  }

  return (
    <>
      <div className="overflow-x-auto">
        <table className="w-full text-sm">
          <thead>
            <tr className="text-white/30 text-xs uppercase tracking-wider border-b border-white/5">
              <th className="text-left py-3 px-4 font-medium">#</th>
              <th className="text-left py-3 px-4 font-medium">Score</th>
              {threshold > 0 && <th className="text-center py-3 px-2 font-medium">THR</th>}
              <th className="text-left py-3 px-4 font-medium">Date</th>
            </tr>
          </thead>
          <tbody>
            {pagedScores.map((s, i) => (
              <tr
                key={s.played_at + i}
                className={`border-b border-white/5 hover:bg-white/[0.02] transition-colors ${threshold > 0 && s.score >= threshold ? 'text-violet-400' : ''}`}
              >
                <td className="py-3 px-4 text-white/30">{totalCount - firstItem - i + 1}</td>
                <td className="py-3 px-4 font-medium">{s.score.toLocaleString()}</td>
                {threshold > 0 && (
                  <td className="py-3 px-2 text-center text-base leading-none">
                    {s.score >= threshold
                      ? <span className="text-emerald-400">✓</span>
                      : <span className="text-white/20">✗</span>}
                  </td>
                )}
                <td className="py-3 px-4 text-white/40">{format(new Date(s.played_at), 'dd/MM/yyyy HH:mm')}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {totalPages > 1 && (
        <div className="flex items-center justify-between px-4 py-3 border-t border-white/5">
          <span className="text-white/30 text-xs">{firstItem}–{lastItem} of {totalCount}</span>
          <div className="flex items-center gap-2">
            <button
              onClick={() => loadPage(page - 1)}
              disabled={page === 1}
              className="px-3 py-1 text-xs text-white/40 hover:text-white disabled:opacity-30 disabled:cursor-not-allowed bg-white/5 hover:bg-white/10 rounded-lg transition-colors"
            >Prev</button>
            <span className="text-white/30 text-xs px-1">{page} / {totalPages}</span>
            <button
              onClick={() => loadPage(page + 1)}
              disabled={page === totalPages}
              className="px-3 py-1 text-xs text-white/40 hover:text-white disabled:opacity-30 disabled:cursor-not-allowed bg-white/5 hover:bg-white/10 rounded-lg transition-colors"
            >Next</button>
          </div>
        </div>
      )}
    </>
  );
}
