// threshold-tracker/apps/web/src/app/components/stats-overview/stats-overview.component.ts
import { Component, Input } from '@angular/core';
import { PlayAttempt } from '../../models/score.model';

@Component({
  selector: 'app-stats-overview',
  standalone: true,
  imports: [],
  templateUrl: './stats-overview.component.html',
})
export class StatsOverviewComponent {
  @Input() scores: PlayAttempt[] = [];
  @Input() threshold = 0;
  @Input() personalBest = 0;

  get totalAttempts() { return this.scores.length; }

  get avgScore() {
    if (!this.scores.length) return 0;
    return Math.round(this.scores.reduce((s, sc) => s + sc.score, 0) / this.scores.length);
  }

  get consistencyPct(): number | null {
    if (!this.threshold || !this.scores.length) return null;
    const above = this.scores.filter(s => s.score >= this.threshold).length;
    return Math.round((above / this.scores.length) * 100);
  }
}

<div class="grid grid-cols-2 lg:grid-cols-4 gap-3">
  <div class="bg-white/[0.03] rounded-xl p-4 border border-white/5">
    <p class="text-white/40 text-xs uppercase tracking-wider mb-2">Tentativas</p>
    <p class="text-white text-xl font-bold">{{ totalAttempts }}</p>
  </div>
  <div class="bg-white/[0.03] rounded-xl p-4 border border-white/5">
    <p class="text-white/40 text-xs uppercase tracking-wider mb-2">Média</p>
    <p class="text-white text-xl font-bold">{{ avgScore > 0 ? avgScore.toLocaleString() : '—' }}</p>
  </div>
  <div class="bg-white/[0.03] rounded-xl p-4 border border-white/5">
    <p class="text-white/40 text-xs uppercase tracking-wider mb-2">PB</p>
    <p class="text-white text-xl font-bold">{{ personalBest ? personalBest.toLocaleString() : '—' }}</p>
  </div>
  <div class="bg-white/[0.03] rounded-xl p-4 border border-white/5">
    <p class="text-white/40 text-xs uppercase tracking-wider mb-2">Consistência</p>
    <p class="text-white text-xl font-bold">{{ consistencyPct !== null ? consistencyPct + '%' : '—' }}</p>
  </div>
</div>

// threshold-tracker/apps/web-react/src/components/StatsOverview.tsx
import { useMemo } from 'react';
import { PlayAttempt } from '../models/score';

interface Props {
  scores: PlayAttempt[];
  threshold: number;
  personalBest: number;
}

export function StatsOverview({ scores, threshold, personalBest }: Props) {
  const totalAttempts = scores.length;

  const avgScore = useMemo(() => {
    if (scores.length === 0) return 0;
    return Math.round(scores.reduce((s, p) => s + p.score, 0) / scores.length);
  }, [scores]);

  const consistencyPct = useMemo(() => {
    if (!threshold || scores.length === 0) return null;
    const above = scores.filter(s => s.score >= threshold).length;
    return Math.round((above / scores.length) * 100);
  }, [scores, threshold]);

  return (
    <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">
      <div className="bg-white/[0.03] rounded-xl p-4 border border-white/5">
        <p className="text-white/40 text-xs uppercase tracking-wider mb-2">Attempts</p>
        <p className="text-white text-xl font-bold">{totalAttempts}</p>
      </div>
      <div className="bg-white/[0.03] rounded-xl p-4 border border-white/5">
        <p className="text-white/40 text-xs uppercase tracking-wider mb-2">Average</p>
        <p className="text-white text-xl font-bold">{avgScore > 0 ? avgScore.toLocaleString() : '—'}</p>
      </div>
      <div className="bg-white/[0.03] rounded-xl p-4 border border-white/5">
        <p className="text-white/40 text-xs uppercase tracking-wider mb-2">PB</p>
        <p className="text-white text-xl font-bold">{personalBest ? personalBest.toLocaleString() : '—'}</p>
      </div>
      <div className="bg-white/[0.03] rounded-xl p-4 border border-white/5">
        <p className="text-white/40 text-xs uppercase tracking-wider mb-2">Consistency</p>
        <p className="text-white text-xl font-bold">{consistencyPct !== null ? `${consistencyPct}%` : '—'}</p>
      </div>
    </div>
  );
}
