// threshold-tracker/apps/web/src/app/components/threshold-indicator/threshold-indicator.component.ts
import { Component, Input } from '@angular/core';
import { NgClass } from '@angular/common';
import { PlayAttempt } from '../../models/score.model';

@Component({
  selector: 'app-threshold-indicator',
  standalone: true,
  imports: [NgClass],
  templateUrl: './threshold-indicator.component.html',
})
export class ThresholdIndicatorComponent {
  @Input() threshold = 0;
  @Input() personalBest = 0;
  @Input() latestScore = 0;
  @Input() scores: PlayAttempt[] = [];

  get max(): number {
    return Math.max(this.threshold, this.personalBest, this.latestScore) * 1.15;
  }
  get thresholdPct(): number { return this.max ? (this.threshold / this.max) * 100 : 0; }
  get pbPct(): number { return this.max ? (this.personalBest / this.max) * 100 : 0; }
  get latestPct(): number { return this.max ? (this.latestScore / this.max) * 100 : 0; }
  get aboveThreshold(): boolean { return !!this.threshold && this.latestScore >= this.threshold; }

  get gapToThreshold(): number {
    if (!this.threshold || !this.latestScore) return 0;
    return this.threshold - this.latestScore;
  }

  get trendDelta(): number {
    if (this.scores.length < 2) return 0;
    const recent = this.scores.slice(-5);
    const prior = this.scores.slice(-10, -5);
    if (prior.length === 0) return 0;
    const avgRecent = recent.reduce((s, p) => s + p.score, 0) / recent.length;
    const avgPrior = prior.reduce((s, p) => s + p.score, 0) / prior.length;
    return Math.round(avgRecent - avgPrior);
  }

  get trendDirection(): 'up' | 'down' | 'stable' {
    if (Math.abs(this.trendDelta) < 10) return 'stable';
    return this.trendDelta > 0 ? 'up' : 'down';
  }
}

<div class="bg-white/[0.03] border border-white/5 rounded-2xl p-6 space-y-5">
  @if (threshold > 0) {
    <!-- Status badge -->
    <div class="flex items-center justify-between">
      @if (aboveThreshold) {
        <span class="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-semibold bg-emerald-500/15 text-emerald-400 border border-emerald-500/20">
          <span class="w-1.5 h-1.5 rounded-full bg-emerald-400"></span>
          ACIMA DA META
        </span>
      } @else {
        <span class="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-semibold bg-rose-500/15 text-rose-400 border border-rose-500/20">
          <span class="w-1.5 h-1.5 rounded-full bg-rose-400"></span>
          ABAIXO DA META
        </span>
      }
      @if (latestScore > 0) {
        <span class="text-2xl font-bold" [ngClass]="aboveThreshold ? 'text-emerald-400' : 'text-rose-400'">
          {{ latestScore.toLocaleString() }}
        </span>
      }
    </div>

    <!-- Gap message -->
    @if (latestScore > 0) {
      <p class="text-sm" [ngClass]="aboveThreshold ? 'text-emerald-400/70' : 'text-white/40'">
        @if (aboveThreshold) {
          {{ (-gapToThreshold).toLocaleString() }} pontos acima da meta
        } @else {
          {{ gapToThreshold.toLocaleString() }} pontos para atingir a meta
        }
      </p>
    }

    <!-- Progress bar -->
    <div class="relative h-5 bg-white/5 rounded-full overflow-visible">
      <!-- PB marker -->
      @if (personalBest > 0) {
        <div class="absolute -top-1 bottom-0 w-0.5 bg-amber-400/60 z-20" [style.left.%]="pbPct"></div>
      }
      <!-- Threshold marker -->
      <div class="absolute -top-1 bottom-0 w-0.5 bg-cyan-400 z-10" [style.left.%]="thresholdPct"></div>
      <!-- Score bar -->
      @if (latestScore > 0) {
        <div class="h-full rounded-full transition-all duration-700"
          [ngClass]="aboveThreshold ? 'bg-gradient-to-r from-emerald-600 to-emerald-400' : 'bg-gradient-to-r from-violet-700 to-violet-500'"
          [style.width.%]="latestPct">
        </div>
      }
    </div>

    <!-- Legend -->
    <div class="flex items-center gap-4 text-xs text-white/40">
      <div class="flex items-center gap-1.5">
        <div class="w-2 h-0.5 bg-cyan-400"></div>
        <span>Meta: {{ threshold.toLocaleString() }}</span>
      </div>
      @if (personalBest > 0) {
        <div class="flex items-center gap-1.5">
          <div class="w-2 h-0.5 bg-amber-400/60"></div>
          <span>PB: {{ personalBest.toLocaleString() }}</span>
        </div>
      }
    </div>

    <!-- Trend pill -->
    @if (scores.length >= 2) {
      <div class="flex items-center gap-2">
        <span class="text-white/30 text-xs">Últimas 5 sessões:</span>
        @if (trendDirection === 'up') {
          <span class="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-xs font-medium bg-emerald-500/10 text-emerald-400 border border-emerald-500/15">
            ↑ +{{ trendDelta }}
          </span>
        } @else if (trendDirection === 'down') {
          <span class="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-xs font-medium bg-rose-500/10 text-rose-400 border border-rose-500/15">
            ↓ {{ trendDelta }}
          </span>
        } @else {
          <span class="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-xs font-medium bg-white/5 text-white/30 border border-white/10">
            — estável
          </span>
        }
      </div>
    }
  } @else {
    <!-- No threshold set -->
    <div class="text-center py-2">
      <p class="text-white/30 text-sm">Nenhuma meta definida para esta task.</p>
      <p class="text-white/20 text-xs mt-1">Defina uma meta nas configurações para acompanhar seu progresso.</p>
    </div>
  }
</div>

// threshold-tracker/apps/web-react/src/components/ThresholdIndicator.tsx
import { useMemo } from 'react';
import { PlayAttempt } from '../models/score';

interface Props {
  threshold: number;
  personalBest: number;
  latestScore: number;
  scores: PlayAttempt[];
}

export function ThresholdIndicator({ threshold, personalBest, latestScore, scores }: Props) {
  const max = Math.max(threshold, personalBest, latestScore) * 1.15;
  const thresholdPct = max ? (threshold / max) * 100 : 0;
  const pbPct = max ? (personalBest / max) * 100 : 0;
  const latestPct = max ? (latestScore / max) * 100 : 0;
  const aboveThreshold = !!threshold && latestScore >= threshold;
  const gapToThreshold = threshold && latestScore ? threshold - latestScore : 0;

  const { trendDelta, trendDirection } = useMemo(() => {
    if (scores.length < 2) return { trendDelta: 0, trendDirection: 'stable' as const };
    const recent = scores.slice(-5);
    const prior = scores.slice(-10, -5);
    if (prior.length === 0) return { trendDelta: 0, trendDirection: 'stable' as const };
    const avgRecent = recent.reduce((s, p) => s + p.score, 0) / recent.length;
    const avgPrior = prior.reduce((s, p) => s + p.score, 0) / prior.length;
    const delta = Math.round(avgRecent - avgPrior);
    const dir = Math.abs(delta) < 10 ? 'stable' : delta > 0 ? 'up' : 'down';
    return { trendDelta: delta, trendDirection: dir as 'up' | 'down' | 'stable' };
  }, [scores]);

  if (!threshold) {
    return (
      <div className="bg-white/[0.03] border border-white/5 rounded-2xl p-6">
        <div className="text-center py-2">
          <p className="text-white/30 text-sm">No threshold set for this task.</p>
          <p className="text-white/20 text-xs mt-1">Set a threshold in the settings below to track your progress.</p>
        </div>
      </div>
    );
  }

  return (
    <div className="bg-white/[0.03] border border-white/5 rounded-2xl p-6 space-y-5">
      {/* Title */}
      <h3 className="text-white/40 text-xs font-medium uppercase tracking-wider">Last Play</h3>
      {/* Status badge */}
      <div className="flex items-center justify-between">
        {aboveThreshold ? (
          <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-semibold bg-emerald-500/15 text-emerald-400 border border-emerald-500/20">
            <span className="w-1.5 h-1.5 rounded-full bg-emerald-400"></span>
            ABOVE GOAL
          </span>
        ) : (
          <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-semibold bg-rose-500/15 text-rose-400 border border-rose-500/20">
            <span className="w-1.5 h-1.5 rounded-full bg-rose-400"></span>
            BELOW GOAL
          </span>
        )}
        {latestScore > 0 && (
          <span className={`text-2xl font-bold ${aboveThreshold ? 'text-emerald-400' : 'text-rose-400'}`}>
            {latestScore.toLocaleString()}
          </span>
        )}
      </div>

      {/* Gap message */}
      {latestScore > 0 && (
        <p className={`text-sm ${aboveThreshold ? 'text-emerald-400/70' : 'text-white/40'}`}>
          {aboveThreshold
            ? `${(-gapToThreshold).toLocaleString()} points above goal`
            : `${gapToThreshold.toLocaleString()} points to reach goal`}
        </p>
      )}

      {/* Progress bar */}
      <div className="relative h-5 bg-white/5 rounded-full overflow-visible">
        {personalBest > 0 && (
          <div className="absolute -top-1 bottom-0 w-0.5 bg-amber-400/60 z-20" style={{ left: `${pbPct}%` }} />
        )}
        <div className="absolute -top-1 bottom-0 w-0.5 bg-cyan-400 z-10" style={{ left: `${thresholdPct}%` }} />
        {latestScore > 0 && (
          <div
            className={`h-full rounded-full transition-all duration-700 ${aboveThreshold ? 'bg-gradient-to-r from-emerald-600 to-emerald-400' : 'bg-gradient-to-r from-violet-700 to-violet-500'}`}
            style={{ width: `${latestPct}%` }}
          />
        )}
      </div>

      {/* Legend */}
      <div className="flex items-center gap-4 text-xs text-white/40">
        <div className="flex items-center gap-1.5">
          <div className="w-2 h-0.5 bg-cyan-400" />
          <span>Goal: {threshold.toLocaleString()}</span>
        </div>
        {personalBest > 0 && (
          <div className="flex items-center gap-1.5">
            <div className="w-2 h-0.5 bg-amber-400/60" />
            <span>PB: {personalBest.toLocaleString()}</span>
          </div>
        )}
      </div>

      {/* Trend pill */}
      {scores.length >= 2 && (
        <div className="flex items-center gap-2">
          <span className="text-white/30 text-xs">Last 5 sessions:</span>
          {trendDirection === 'up' && (
            <span className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-xs font-medium bg-emerald-500/10 text-emerald-400 border border-emerald-500/15">
              ↑ +{trendDelta}
            </span>
          )}
          {trendDirection === 'down' && (
            <span className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-xs font-medium bg-rose-500/10 text-rose-400 border border-rose-500/15">
              ↓ {trendDelta}
            </span>
          )}
          {trendDirection === 'stable' && (
            <span className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-xs font-medium bg-white/5 text-white/30 border border-white/10">
              — stable
            </span>
          )}
        </div>
      )}
    </div>
  );
}
