// threshold-tracker/apps/web/src/app/components/threshold-settings/threshold-settings.component.ts
import { Component, Input, Output, EventEmitter, OnInit, signal } from '@angular/core';
import { UserTaskStat } from '../../models/task.model';
import { PlayAttempt } from '../../models/score.model';

@Component({
  selector: 'app-threshold-settings',
  standalone: true,
  imports: [],
  templateUrl: './threshold-settings.component.html',
})
export class ThresholdSettingsComponent implements OnInit {
  @Input() task!: UserTaskStat;
  @Input() scores: PlayAttempt[] = [];
  @Output() save = new EventEmitter<number>();

  value = signal('');
  saving = signal(false);
  suggested = signal<number | null>(null);

  ngOnInit() {
    this.value.set(this.task.threshold_value?.toString() || '');
    this.suggested.set(this.calculateSuggested());
  }

  calculateSuggested(): number | null {
    if (this.scores.length < 5) return null;
    const values = this.scores.map(s => s.score).sort((a, b) => a - b);
    const trimCount = Math.max(1, Math.floor(values.length * 0.1));
    const trimmed = values.slice(trimCount, values.length - trimCount);
    return Math.round(trimmed[Math.floor(trimmed.length * 0.75)]);
  }

  onSave() {
    const num = parseFloat(this.value());
    if (!num || num <= 0) return;
    this.saving.set(true);
    this.save.emit(num);
    this.saving.set(false);
  }
}

<div class="space-y-4">
  <div class="space-y-2">
    <label class="text-white/60 text-xs uppercase tracking-wider">Threshold</label>
    <div class="flex gap-2">
      <input type="number" [value]="value()" (input)="value.set($any($event.target).value)"
        placeholder="Defina o threshold..."
        class="flex-1 px-3 py-2 bg-white/5 border border-white/10 rounded-lg text-white placeholder-white/20 outline-none focus:border-white/20" />
      <button (click)="onSave()" [disabled]="!value() || saving()"
        class="flex items-center gap-2 px-4 py-2 bg-cyan-600 hover:bg-cyan-500 text-white rounded-lg font-medium disabled:opacity-50">
        Salvar
      </button>
    </div>
  </div>

  <!-- Autosync toggle -->
  <label class="flex items-center gap-3 cursor-pointer group">
    <div class="relative">
      <input type="checkbox" class="sr-only" [checked]="autosyncEnabled()"
        (change)="autosyncEnabled.set($any($event.target).checked)" />
      <div class="w-9 h-5 rounded-full transition-colors"
        [class.bg-violet-600]="autosyncEnabled()"
        [class.bg-white/10]="!autosyncEnabled()">
      </div>
      <div class="absolute top-0.5 left-0.5 w-4 h-4 bg-white rounded-full transition-transform shadow"
        [class.translate-x-4]="autosyncEnabled()">
      </div>
    </div>
    <span class="text-white/60 text-sm group-hover:text-white/80 transition-colors">
      Recalcular automaticamente (1x por dia)
    </span>
  </label>

  @if (suggested()) {
    <div class="space-y-1.5">
      <button (click)="value.set(suggested()!.toString())"
        class="flex items-center gap-2 text-sm text-amber-400/80 hover:text-amber-400 transition-colors">
        💡 Threshold sugerido: <strong>{{ suggested()!.toLocaleString() }}</strong>
        <span class="text-white/30 ml-1">(últimas {{ suggestedWindowSize }} tentativas)</span>
      </button>
      <p class="text-white/25 text-xs pl-0.5">
        Melhor pontuação consistente excluindo picos de sorte — o que você consegue repetir com esforço focado.
      </p>
    </div>
  }
  @if (scores.length < 5 && scores.length > 0) {
    <p class="text-white/20 text-xs">
      Registre pelo menos 5 pontuações para receber uma sugestão de threshold
    </p>
  }
</div>

// threshold-tracker/apps/web-react/src/components/ThresholdSettings.tsx
import { useState, useEffect } from 'react';
import { UserTaskStat } from '../models/task';
import { PlayAttempt } from '../models/score';
import { calculateThreshold, suggestedWindowSize } from '../utils/threshold';

interface Props {
  task: UserTaskStat;
  scores: PlayAttempt[];
  onSave: (data: { value: number; autosyncEnabled: boolean }) => void;
}

export function ThresholdSettings({ task, scores, onSave }: Props) {
  const [value, setValue] = useState(task.threshold_value?.toString() ?? '');
  const [autosyncEnabled, setAutosyncEnabled] = useState(task.autosync_enabled ?? true);
  const suggested = scores.length >= 5 ? calculateThreshold(scores) : null;
  const windowSize = suggestedWindowSize(scores);

  useEffect(() => {
    setValue(task.threshold_value?.toString() ?? '');
    setAutosyncEnabled(task.autosync_enabled ?? true);
  }, [task.aimlabs_task_id]);

  function handleSave() {
    const num = parseFloat(value);
    if (!num || num <= 0) return;
    onSave({ value: num, autosyncEnabled });
  }

  return (
    <div className="space-y-4">
      <div className="space-y-2">
        <label className="text-white/60 text-xs uppercase tracking-wider">Threshold</label>
        <div className="flex gap-2">
          <input
            type="number"
            value={value}
            onChange={e => setValue(e.target.value)}
            placeholder="Set your threshold..."
            className="flex-1 px-3 py-2 bg-white/5 border border-white/10 rounded-lg text-white placeholder-white/20 outline-none focus:border-white/20"
          />
          <button
            onClick={handleSave}
            disabled={!value}
            className="flex items-center gap-2 px-4 py-2 bg-cyan-600 hover:bg-cyan-500 text-white rounded-lg font-medium disabled:opacity-50"
          >
            Save
          </button>
        </div>
      </div>

      {/* Autosync toggle */}
      <label className="flex items-center gap-3 cursor-pointer group">
        <div className="relative">
          <input
            type="checkbox"
            className="sr-only"
            checked={autosyncEnabled}
            onChange={e => setAutosyncEnabled(e.target.checked)}
          />
          <div className={`w-9 h-5 rounded-full transition-colors ${autosyncEnabled ? 'bg-violet-600' : 'bg-white/10'}`} />
          <div className={`absolute top-0.5 left-0.5 w-4 h-4 bg-white rounded-full transition-transform shadow ${autosyncEnabled ? 'translate-x-4' : ''}`} />
        </div>
        <span className="text-white/60 text-sm group-hover:text-white/80 transition-colors">
          Auto-recalculate (once per day)
        </span>
      </label>

      {suggested && (
        <div className="space-y-1.5">
          <button
            onClick={() => setValue(suggested.toString())}
            className="flex items-center gap-2 text-sm text-amber-400/80 hover:text-amber-400 transition-colors"
          >
            💡 Suggested threshold: <strong>{suggested.toLocaleString()}</strong>
            <span className="text-white/30 ml-1">(last {windowSize} attempts)</span>
          </button>
          <p className="text-white/25 text-xs pl-0.5">
            Best consistent score excluding lucky peaks — what you can repeat with focused effort.
          </p>
        </div>
      )}

      {scores.length < 5 && scores.length > 0 && (
        <p className="text-white/20 text-xs">
          Record at least 5 scores to receive a threshold suggestion.
        </p>
      )}
    </div>
  );
}
