// threshold-tracker/apps/web-react/src/components/TaskCard.tsx
import { Link } from 'react-router-dom';
import { UserTaskStat } from '../models/task';
import { categoryColorClass, categoryTextColor } from '../utils/categoryColors';

function getTrend(task: UserTaskStat): 'up' | 'down' | 'stable' | 'none' {
  if (task.last5_avg == null || task.avg_score == null) return 'none';
  const delta = task.last5_avg - task.avg_score;
  if (delta > 50) return 'up';
  if (delta < -50) return 'down';
  return 'stable';
}

export function TaskCard({ task }: { task: UserTaskStat }) {
  const colorClass = categoryColorClass(task.category);
  const textColor = categoryTextColor(task.category);
  const trend = getTrend(task);

  return (
    <Link to={`/task/${task.aimlabs_task_id}`}>
      <div className={`group relative bg-gradient-to-br border rounded-2xl p-5 hover:scale-[1.02] transition-all duration-300 cursor-pointer ${colorClass}`}>
        <div className="flex items-start justify-between mb-4">
          <div className={`p-2.5 rounded-xl bg-black/30 ${textColor}`}>
            <svg xmlns="http://www.w3.org/2000/svg" className="w-5 h-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <circle cx="12" cy="12" r="10"/><line x1="22" y1="12" x2="18" y2="12"/>
              <line x1="6" y1="12" x2="2" y2="12"/><line x1="12" y1="6" x2="12" y2="2"/>
              <line x1="12" y1="22" x2="12" y2="18"/>
            </svg>
          </div>
          <span className="text-xs font-medium text-white/40 uppercase tracking-wider">{task.category}</span>
        </div>

        <h3 className="text-white font-semibold text-lg mb-3 truncate">{task.task_name}</h3>

        <div className="grid grid-cols-4 gap-2">
          <div>
            <p className="text-white/40 text-xs mb-0.5">Threshold</p>
            <p className={`text-base font-bold ${task.threshold_value ? textColor : 'text-white/20'}`}>
              {task.threshold_value ? task.threshold_value.toLocaleString() : '—'}
            </p>
          </div>
          <div>
            <p className="text-white/40 text-xs mb-0.5">PB</p>
            <p className="text-base font-bold text-white/80">
              {task.personal_best ? task.personal_best.toLocaleString() : '—'}
            </p>
          </div>
          <div>
            <p className="text-white/40 text-xs mb-0.5">Plays</p>
            <p className="text-base font-bold text-white/50">{task.play_count.toLocaleString()}</p>
          </div>
          <div>
            <p className="text-white/40 text-xs mb-0.5">Trend</p>
            {trend === 'up' && <p className="text-emerald-400 text-base font-bold">↑</p>}
            {trend === 'down' && <p className="text-rose-400 text-base font-bold">↓</p>}
            {(trend === 'stable' || trend === 'none') && <p className="text-white/20 text-base font-bold">—</p>}
          </div>
        </div>
      </div>
    </Link>
  );
}

// threshold-tracker/apps/web/src/app/components/task-card/task-card.component.ts
import { Component, Input } from '@angular/core';
import { RouterLink } from '@angular/router';
import { NgClass } from '@angular/common';
import { UserTaskStat } from '../../models/task.model';

@Component({
  selector: 'app-task-card',
  standalone: true,
  imports: [RouterLink, NgClass],
  templateUrl: './task-card.component.html',
})
export class TaskCardComponent {
  @Input() task!: UserTaskStat;

  get colorClass(): string {
    const map: Record<string, string> = {
      tracking: 'from-cyan-500/20 to-cyan-500/5 border-cyan-500/30',
      flicking: 'from-violet-500/20 to-violet-500/5 border-violet-500/30',
      switching: 'from-amber-500/20 to-amber-500/5 border-amber-500/30',
      clicking: 'from-rose-500/20 to-rose-500/5 border-rose-500/30',
      other: 'from-slate-500/20 to-slate-500/5 border-slate-500/30',
    };
    return map[this.task.category] || map['other'];
  }

  get textColor(): string {
    const map: Record<string, string> = {
      tracking: 'text-cyan-400', flicking: 'text-violet-400',
      switching: 'text-amber-400', clicking: 'text-rose-400', other: 'text-slate-400',
    };
    return map[this.task.category] || 'text-slate-400';
  }

  get trend(): 'up' | 'down' | 'stable' | 'none' {
    if (this.task.last5_avg == null || this.task.avg_score == null) return 'none';
    const delta = this.task.last5_avg - this.task.avg_score;
    if (delta > 50) return 'up';
    if (delta < -50) return 'down';
    return 'stable';
  }
}

<a [routerLink]="['/task', task.aimlabs_task_id]">
  <div class="group relative bg-gradient-to-br border rounded-2xl p-5 hover:scale-[1.02] transition-all duration-300 cursor-pointer"
    [ngClass]="colorClass">
    <div class="flex items-start justify-between mb-4">
      <div class="p-2.5 rounded-xl bg-black/30" [ngClass]="textColor">
        <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5" viewBox="0 0 24 24"
          fill="none" stroke="currentColor" stroke-width="2">
          <circle cx="12" cy="12" r="10"/><line x1="22" y1="12" x2="18" y2="12"/>
          <line x1="6" y1="12" x2="2" y2="12"/><line x1="12" y1="6" x2="12" y2="2"/>
          <line x1="12" y1="22" x2="12" y2="18"/>
        </svg>
      </div>
      <span class="text-xs font-medium text-white/40 uppercase tracking-wider">{{ task.category }}</span>
    </div>

    <h3 class="text-white font-semibold text-lg mb-3 truncate">{{ task.task_name }}</h3>

    <div class="grid grid-cols-4 gap-2">
      <div>
        <p class="text-white/40 text-xs mb-0.5">Threshold</p>
        <p class="text-base font-bold" [ngClass]="task.threshold_value ? textColor : 'text-white/20'">
          {{ task.threshold_value ? task.threshold_value.toLocaleString() : '—' }}
        </p>
      </div>
      <div>
        <p class="text-white/40 text-xs mb-0.5">PB</p>
        <p class="text-base font-bold text-white/80">
          {{ task.personal_best ? task.personal_best.toLocaleString() : '—' }}
        </p>
      </div>
      <div>
        <p class="text-white/40 text-xs mb-0.5">Plays</p>
        <p class="text-base font-bold text-white/50">{{ task.play_count.toLocaleString() }}</p>
      </div>
      <div>
        <p class="text-white/40 text-xs mb-0.5">Trend</p>
        @if (trend === 'up') {
          <p class="text-emerald-400 text-base font-bold">↑</p>
        } @else if (trend === 'down') {
          <p class="text-rose-400 text-base font-bold">↓</p>
        } @else {
          <p class="text-white/20 text-base font-bold">—</p>
        }
      </div>
    </div>
  </div>
</a>
